# Generated by Django 5.2.16 on 2026-08-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_note',
            field=models.TextField(blank=True),
        ),
    ]
