from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("register/password-check/", views.registration_password_check, name="registration_password_check"),
    path("forgot-password/", views.forgot_password_request, name="forgot_password"),
    path("forgot-password/done/", views.forgot_password_done, name="forgot_password_done"),
    path("users/", views.user_list, name="users"),
    path("users/add/", views.user_add, name="user_add"),
    path("users/<int:pk>/edit/", views.user_edit, name="user_edit"),
    path("users/<int:pk>/deactivate/", views.user_deactivate, name="user_deactivate"),
    path("users/<int:pk>/action/", views.user_action, name="user_action"),
    path("users/password-resets/<int:pk>/", views.password_reset_review, name="password_reset_review"),
    path("users/password-resets/<int:pk>/reject/", views.password_reset_reject, name="password_reset_reject"),
    path("profile/", views.profile, name="profile"),
    path("password/", auth_views.PasswordChangeView.as_view(template_name="users/password_change.html", success_url="/profile/"), name="password_change"),
    path("scopes/", views.scope_settings, name="scopes"),
    path("scopes/<int:pk>/edit/", views.scope_edit, name="scope_edit"),
    path("scopes/<int:pk>/delete/", views.scope_delete, name="scope_delete"),
    path("boards/", views.board_list, name="boards"),
    path("boards/add/", views.board_form, name="board_add"),
    path("boards/<int:pk>/edit/", views.board_form, name="board_edit"),
    path("boards/<int:pk>/delete/", views.board_delete, name="board_delete"),
    path("boards/<int:pk>/users/", views.board_user_action, name="board_user_action"),
    path("boards/<int:pk>/history/", views.board_history, name="board_history"),
    path("tasks/", views.task_list, name="tasks"),
    path("tasks/timeline/", views.task_timeline, name="task_timeline"),
    path("tasks/timeline/tasks/<int:pk>/", views.timeline_task_update, name="timeline_task_update"),
    path("tasks/timeline/groups/add/", views.timeline_group_add, name="timeline_group_add"),
    path("tasks/timeline/groups/<int:pk>/edit/", views.timeline_group_edit, name="timeline_group_edit"),
    path("tasks/timeline/groups/<int:pk>/delete/", views.timeline_group_delete, name="timeline_group_delete"),
    path("tasks/timeline/holidays/add/", views.timeline_holiday_add, name="timeline_holiday_add"),
    path("tasks/timeline/holidays/<int:pk>/edit/", views.timeline_holiday_edit, name="timeline_holiday_edit"),
    path("tasks/timeline/holidays/<int:pk>/delete/", views.timeline_holiday_delete, name="timeline_holiday_delete"),
    path("tasks/timeline/milestones/add/", views.timeline_milestone_add, name="timeline_milestone_add"),
    path("tasks/timeline/milestones/<int:pk>/edit/", views.timeline_milestone_edit, name="timeline_milestone_edit"),
    path("tasks/timeline/milestones/<int:pk>/delete/", views.timeline_milestone_delete, name="timeline_milestone_delete"),
    path("tasks/add/", views.task_form, name="task_add"),
    path("tasks/<int:pk>/edit/", views.task_form, name="task_edit"),
    path("tasks/<int:pk>/delete/", views.task_delete, name="task_delete"),
    path("tasks/<int:pk>/history/", views.task_history, name="task_history"),
    path("action-items/<int:pk>/toggle/", views.action_item_toggle, name="action_item_toggle"),
    path("meetings/", views.meeting_list, name="meetings"),
    path("meetings/minute-writers/", views.minute_writer_rotation_list, name="minute_writer_rotations"),
    path("meetings/minute-writers/add/", views.minute_writer_rotation_form, name="minute_writer_rotation_add"),
    path("meetings/minute-writers/<int:pk>/edit/", views.minute_writer_rotation_form, name="minute_writer_rotation_edit"),
    path("meetings/minute-writers/<int:pk>/delete/", views.minute_writer_rotation_delete, name="minute_writer_rotation_delete"),
    path("meetings/minute-writers/preview/", views.minute_writer_preview, name="minute_writer_preview"),
    path("meetings/add/", views.meeting_create, name="meeting_add"),
    path("meetings/<int:pk>/", views.meeting_detail, name="meeting_detail"),
    path("meetings/<int:pk>/export.pdf", views.meeting_export_pdf, name="meeting_export_pdf"),
    path("meetings/<int:pk>/edit/", views.meeting_edit, name="meeting_edit"),
    path("meetings/<int:pk>/delete/", views.meeting_delete, name="meeting_delete"),
    path("meetings/<int:pk>/finalize/", views.meeting_finalize, name="meeting_finalize"),
    path("meetings/<int:pk>/reopen/", views.meeting_reopen, name="meeting_reopen"),
    path("meetings/<int:pk>/order/", views.meeting_order, name="meeting_order"),
    path("meetings/<int:meeting_pk>/tasks/<int:entry_pk>/progress/", views.meeting_task_progress_save, name="meeting_task_progress_save"),
    path("meetings/<int:meeting_pk>/tasks/<int:entry_pk>/actions/", views.meeting_action_add, name="meeting_action_add"),
    path("meetings/<int:meeting_pk>/actions/<int:pk>/update/", views.meeting_action_update, name="meeting_action_update"),
    path("meetings/<int:meeting_pk>/actions/<int:pk>/delete/", views.meeting_action_delete, name="meeting_action_delete"),
    path("meetings/<int:meeting_pk>/tasks/<int:entry_pk>/review/", views.meeting_task_review, name="meeting_task_review"),
    path("meetings/<int:meeting_pk>/tasks/<int:entry_pk>/move/", views.meeting_task_move, name="meeting_task_move"),
    path("meetings/<int:pk>/live/", views.meeting_live_updates, name="meeting_live_updates"),
]
