#!/bin/sh
# Shared by scheduler/manual tools; optional Git upload uses backup.Dockerfile.
set -eu
umask 077
BACKUP_INTERVAL_SECONDS=${BACKUP_INTERVAL_SECONDS:-86400}
BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-30}
stage=
scratch=
validation_db=
cleanup() {
    if [ -n "$validation_db" ]; then
        dropdb -h backup_verify -U backup_verify --if-exists "$validation_db" >/dev/null 2>&1 || true
    fi
    # These paths are exclusively generated by mktemp inside this process.
    [ -z "$stage" ] || rm -rf -- "$stage"
    [ -z "$scratch" ] || rm -rf -- "$scratch"
}
finish() {
    status=$?
    if [ "$status" -ne 0 ] && { [ "${mode:-}" = once ] || [ "${mode:-}" = push ]; }; then
        date -u +%Y-%m-%dT%H:%M:%SZ > /backups/.last-failure
    fi
    cleanup
    exit "$status"
}
trap finish EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
die() { echo "$*" >&2; exit 1; }
positive() {
    printf '%s\n' "$2" | grep -Eq '^[1-9][0-9]*$' || die "$1 must be a positive integer without leading zeros"
}
positive BACKUP_INTERVAL_SECONDS "$BACKUP_INTERVAL_SECONDS"
positive BACKUP_RETENTION_DAYS "$BACKUP_RETENTION_DAYS"
valid_id() {
    # Only completed, generated bundle identifiers; never arbitrary paths.
    printf '%s\n' "$1" | grep -Eq '^mmp-[0-9]{8}T[0-9]{6}Z-[a-zA-Z0-9]{6}$' || die 'Invalid bundle ID'
}
bundle_path() {
    valid_id "$1"
    [ -d "/backups/$1" ] && [ ! -L "/backups/$1" ] || die 'Bundle not found'
    bundle="/backups/$1"
}
check_bundle() {
    candidate=$1
    for file in database.dump media.tar.gz manifest.txt checksums.sha256; do
        [ -f "$candidate/$file" ] && [ ! -L "$candidate/$file" ] || die "Missing or unsafe $file"
    done
    # Compare only fixed filenames, never execute arbitrary paths from a manifest.
    scratch=$(mktemp -d /tmp/mmp-verify.XXXXXX)
    (cd "$candidate"; sha256sum database.dump media.tar.gz manifest.txt) > "$scratch/checksums"
    cmp "$candidate/checksums.sha256" "$scratch/checksums" || die 'Checksum mismatch'
    tar -tzf "$candidate/media.tar.gz" > "$scratch/names"
    awk '/^\// || /(^|\/)\.\.(\/|$)/ {exit 1}' "$scratch/names" || die 'Unsafe media path'
    tar -tvzf "$candidate/media.tar.gz" > "$scratch/types"
    awk 'substr($0,1,1) != "-" && substr($0,1,1) != "d" {exit 1}' "$scratch/types" || die 'Media links and special files are not supported'
    mkdir "$scratch/media"
    tar -xzf "$candidate/media.tar.gz" -C "$scratch/media"
    validation_db="verify_$(date +%s)_$(basename "$scratch" | tr -cd 'a-zA-Z0-9')"
    createdb -h backup_verify -U backup_verify "$validation_db"
    pg_restore -h backup_verify -U backup_verify -d "$validation_db" \
        --no-owner --no-privileges --exit-on-error --single-transaction "$candidate/database.dump"
    dropdb -h backup_verify -U backup_verify "$validation_db"
    validation_db=
    rm -rf -- "$scratch"
    scratch=
}
prune() {
    root=$1
    keep=$2
    # Never touch legacy dumps, partial directories, or the newly successful bundle.
    find "$root" -mindepth 1 -maxdepth 1 -type d -name 'mmp-*' -mtime "+$BACKUP_RETENTION_DAYS" |
    while IFS= read -r old; do
        id=$(basename "$old")
        if [ "$id" != "$keep" ] && [ "$id" != "${BACKUP_PROTECT_ID:-}" ] && [ ! -e "$old/.git-pending" ] && printf '%s\n' "$id" | grep -Eq '^mmp-[0-9]{8}T[0-9]{6}Z-[a-zA-Z0-9]{6}$' && [ -f "$old/checksums.sha256" ]; then
            rm -rf -- "$old"
        fi
    done
}
flush_git() {
    [ "${BACKUP_GIT_ENABLED:-0}" = 1 ] || return 0
    for pending in /backups/mmp-*/.git-pending; do
        [ -e "$pending" ] || continue
        [ -f "$pending" ] && [ ! -L "$pending" ] || die 'Unsafe upload queue entry'
        pending_id=$(basename "$(dirname "$pending")")
        bundle_path "$pending_id"
        check_bundle "$bundle"
        /bin/sh /opt/backup-git.sh "$pending_id"
        rm -- "$pending"
    done
}
mark_success() {
    # Only clear failure when the latest capture reached EVERY configured target.
    # A later successful Git retry cannot hide a failed NAS export.
    [ -f /backups/.last-capture-id ] && [ -f /backups/.last-ready ] || return 0
    [ "$(cat /backups/.last-capture-id)" = "$(cat /backups/.last-ready)" ] || return 0
    if [ "${BACKUP_GIT_ENABLED:-0}" = 1 ]; then
        for pending in /backups/mmp-*/.git-pending; do
            [ ! -e "$pending" ] || return 0
        done
    fi
    cp /backups/.last-capture /backups/.last-success.tmp
    mv /backups/.last-success.tmp /backups/.last-success
    rm -f /backups/.last-failure
}
make_backup() {
    stage=$(mktemp -d /backups/.partial.XXXXXX)
    id="mmp-$(date -u +%Y%m%dT%H%M%SZ)-${stage##*.}"
    pg_dump -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Fc -f "$stage/database.dump"
    # Avoid files that can redirect extraction outside its staging directory.
    if [ -n "$(find /media ! -type d ! -type f -print -quit)" ]; then
        die 'Media contains a link or special file; backup aborted'
    fi
    tar -czf "$stage/media.tar.gz" -C /media .
    printf 'format=1\ncreated_at=%s\ndatabase=%s\ncapture=%s\napp_version=%s\n' \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$POSTGRES_DB" "${BACKUP_CAPTURE_MODE:-online}" "${APP_VERSION:-unknown}" > "$stage/manifest.txt"
    (cd "$stage"; sha256sum database.dump media.tar.gz manifest.txt > checksums.sha256)
    check_bundle "$stage"
    # Publish the pending flag atomically with the bundle, so crashes cannot lose
    # a verified backup between publication and queue registration.
    if [ "${BACKUP_GIT_ENABLED:-0}" = 1 ]; then
        touch "$stage/.git-pending"
    fi
    mv "$stage" "/backups/$id"
    stage=
    date +%s > /backups/.last-capture.tmp
    mv /backups/.last-capture.tmp /backups/.last-capture
    printf '%s\n' "$id" > /backups/.last-capture-id.tmp
    mv /backups/.last-capture-id.tmp /backups/.last-capture-id
    if [ "${BACKUP_EXPORT_ENABLED:-0}" = 1 ]; then
        [ -d /exports ] && [ -w /exports ] || die 'Export destination unavailable'
        stage=$(mktemp -d /exports/.partial.XXXXXX)
        for file in database.dump media.tar.gz manifest.txt checksums.sha256; do
            cp "/backups/$id/$file" "$stage/"
        done
        check_bundle "$stage"
        mv "$stage" "/exports/$id"
        stage=
        prune /exports "$id"
    fi
    printf '%s\n' "$id" > /backups/.last-ready.tmp
    mv /backups/.last-ready.tmp /backups/.last-ready
    flush_git
    # Health only becomes successful after all configured destinations succeed.
    mark_success
    prune /backups "$id"
    echo "Backup verified: $id"
    backup_id=$id
}
restore_bundle() {
    bundle_path "$1"
    target=$bundle
    check_bundle "$target"
    # The host wrapper has stopped all writers. Mandatory independent recovery copy.
    BACKUP_PROTECT_ID=$1 BACKUP_CAPTURE_MODE=quiesced make_backup
    recovery_id=$backup_id
    echo "Recovery backup: $recovery_id"
    restore_stage=$(mktemp -d /media/.mmp-restore.XXXXXX)
    echo "Media staging (preserved on failure): $restore_stage"
    mkdir "$restore_stage/new" "$restore_stage/old"
    tar -xzf "$target/media.tar.gz" -C "$restore_stage/new"
    # Recreate, rather than --clean: tables introduced after this dump must disappear.
    # No automatic restart on failure: the recovery bundle remains available.
    dropdb -h db -U "$POSTGRES_USER" --maintenance-db=template1 --force "$POSTGRES_DB"
    createdb -h db -U "$POSTGRES_USER" --maintenance-db=template1 --template=template0 "$POSTGRES_DB"
    pg_restore -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" --no-owner \
        --no-privileges --exit-on-error --single-transaction "$target/database.dump"
    for entry in /media/* /media/.[!.]* /media/..?*; do
        [ -e "$entry" ] || continue
        [ "$entry" != "$restore_stage" ] || continue
        mv -- "$entry" "$restore_stage/old/"
    done
    for entry in "$restore_stage/new/"* "$restore_stage/new/".[!.]* "$restore_stage/new/"..?*; do
        [ -e "$entry" ] || continue
        mv -- "$entry" /media/
    done
    rm -rf -- "$restore_stage"
    echo "Restored: $1 (recovery: $recovery_id)"
}
mode=${1:-watch}
if [ "$mode" = health ]; then
    [ ! -f /backups/.last-failure ] && [ -f /backups/.last-success ] || exit 1
    if [ "${BACKUP_GIT_ENABLED:-0}" = 1 ]; then
        for pending in /backups/mmp-*/.git-pending; do
            [ ! -e "$pending" ] || exit 1
        done
    fi
    success=$(cat /backups/.last-success)
    case "$success" in ''|*[!0-9]*) exit 1;; esac
    age=$(( $(date +%s) - success ))
    [ "$age" -ge 0 ] && [ "$age" -lt "$((BACKUP_INTERVAL_SECONDS + 3600))" ]
    exit
fi
mkdir -p /backups
# Kernel lock is automatically released on a crash; manual and scheduled jobs serialize.
exec 9>/backups/.backup.lock
case "$mode" in
    watch)
        first=1
        while true; do
            if [ "${BACKUP_GIT_ENABLED:-0}" = 1 ]; then
                last_capture=0
                [ ! -f /backups/.last-capture ] || last_capture=$(cat /backups/.last-capture)
                printf '%s\n' "$last_capture" | grep -Eq '^[0-9]+$' || last_capture=0
                next_capture=$((last_capture + BACKUP_INTERVAL_SECONDS))
                if [ "$first" = 1 ] || [ "$(date +%s)" -ge "$next_capture" ]; then
                    if /bin/sh "$0" once; then :; else echo 'Backup target failed; queued uploads will retry' >&2; fi
                else
                    if /bin/sh "$0" push; then :; else echo 'Git upload failed; retaining pending bundles' >&2; fi
                fi
                first=0
                last_capture=$(cat /backups/.last-capture 2>/dev/null || echo 0)
                delay=$((last_capture + BACKUP_INTERVAL_SECONDS - $(date +%s)))
                if [ "$delay" -le 0 ]; then delay=1; elif [ "$delay" -gt 60 ]; then delay=60; fi
                sleep "$delay"
                continue
            fi
            # A fresh shell preserves errexit; conditional function calls do not.
            if /bin/sh "$0" once; then :; else
                echo 'Backup failed; retrying in 60 seconds' >&2
                sleep 60
                continue
            fi
            sleep "$BACKUP_INTERVAL_SECONDS"
        done;;
    once) flock -x 9; make_backup;;
    push)
        flock -x 9
        [ "${BACKUP_GIT_ENABLED:-0}" = 1 ] || die 'Git upload is not enabled'
        if [ -n "${2:-}" ]; then
            bundle_path "$2"
            check_bundle "$bundle"
            touch "$bundle/.git-pending"
        fi
        flush_git
        mark_success;;
    verify) flock -x 9; bundle_path "${2:?Bundle ID required}"; check_bundle "$bundle"; echo "Verified: $2";;
    import)
        flock -x 9
        valid_id "${2:?Bundle ID required}"
        check_bundle /import
        if [ -e "/backups/$2" ]; then
            bundle_path "$2"
            check_bundle "$bundle"
            cmp /import/checksums.sha256 "$bundle/checksums.sha256" || die 'Existing bundle differs; refusing overwrite'
        else
            stage=$(mktemp -d /backups/.partial.XXXXXX)
            for file in database.dump media.tar.gz manifest.txt checksums.sha256; do
                cp "/import/$file" "$stage/"
            done
            check_bundle "$stage"
            mv "$stage" "/backups/$2"
            stage=
        fi
        echo "Imported: $2";;
    restore) flock -x 9; restore_bundle "${2:?Bundle ID required}";;
    list) find /backups -mindepth 1 -maxdepth 1 -type d -name 'mmp-*' | sort;;
    *) die 'Usage: backup-worker.sh watch|once|health|list|verify ID|restore ID|import ID|push [ID]';;
esac
